language: node_js
node_js:
  - 8.10.0

script: npm run build

deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: youngvotescount.org-production
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
